[package]
name = "sah31m/draco-knit"
description = "Knit with functions GetLibrary & GetModule to make modular usage more fluid."
version = "0.1.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^1"
Promise = "evaera/promise@^4"